# -*- coding: utf-8 -*-

from PyQt5 import QtCore, QtWidgets
import sys

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("访问数据库")
        Form.resize(600, 400)
        self.verticalLayoutWidget = QtWidgets.QWidget(Form)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 20, 581, 361))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_id = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_id.setMaximumSize(QtCore.QSize(50, 30))
        self.label_id.setObjectName("label_id")
        self.horizontalLayout.addWidget(self.label_id)
        self.lineEdit_id = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.lineEdit_id.setMaximumSize(QtCore.QSize(100, 20))
        self.lineEdit_id.setObjectName("lineEdit_id")
        self.horizontalLayout.addWidget(self.lineEdit_id)
        self.label_pname = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_pname.setMaximumSize(QtCore.QSize(50, 30))
        self.label_pname.setObjectName("label_pname")
        self.horizontalLayout.addWidget(self.label_pname)
        self.lineEdit_pname = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.lineEdit_pname.setMaximumSize(QtCore.QSize(100, 16777215))
        self.lineEdit_pname.setObjectName("lineEdit_pname")
        self.horizontalLayout.addWidget(self.lineEdit_pname)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_brand = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_brand.setMaximumSize(QtCore.QSize(50, 30))
        self.label_brand.setObjectName("label_brand")
        self.horizontalLayout_2.addWidget(self.label_brand)
        self.lineEdit_brand = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.lineEdit_brand.setMaximumSize(QtCore.QSize(100, 20))
        self.lineEdit_brand.setObjectName("lineEdit_brand")
        self.horizontalLayout_2.addWidget(self.lineEdit_brand)
        self.label_price = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_price.setMaximumSize(QtCore.QSize(50, 30))
        self.label_price.setObjectName("label_price")
        self.horizontalLayout_2.addWidget(self.label_price)
        self.lineEdit_price = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.lineEdit_price.setMaximumSize(QtCore.QSize(100, 16777215))
        self.lineEdit_price.setObjectName("lineEdit_price")
        self.horizontalLayout_2.addWidget(self.lineEdit_price)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.horizontalLayout_3.setContentsMargins(1, -1, 272, -1)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_stock = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_stock.setMaximumSize(QtCore.QSize(50, 30))
        self.label_stock.setObjectName("label_stock")
        self.horizontalLayout_3.addWidget(self.label_stock)
        self.lineEdit_stock = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.lineEdit_stock.setMaximumSize(QtCore.QSize(100, 20))
        self.lineEdit_stock.setObjectName("lineEdit_stock")
        self.horizontalLayout_3.addWidget(self.lineEdit_stock)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.horizontalLayout_4.setContentsMargins(0, -1, 0, -1)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.pushButton_first = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton_first.setMaximumSize(QtCore.QSize(70, 30))
        self.pushButton_first.setObjectName("pushButton_first")
        self.horizontalLayout_4.addWidget(self.pushButton_first)
        self.pushButton_pre = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton_pre.setMaximumSize(QtCore.QSize(70, 30))
        self.pushButton_pre.setObjectName("pushButton_pre")
        self.horizontalLayout_4.addWidget(self.pushButton_pre)
        self.pushButton_next = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton_next.setMaximumSize(QtCore.QSize(70, 30))
        self.pushButton_next.setObjectName("pushButton_next")
        self.horizontalLayout_4.addWidget(self.pushButton_next)
        self.pushButton_last = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton_last.setMaximumSize(QtCore.QSize(90, 30))
        self.pushButton_last.setObjectName("pushButton_last")
        self.horizontalLayout_4.addWidget(self.pushButton_last)
        self.pushButton_insert = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton_insert.setMaximumSize(QtCore.QSize(60, 30))
        self.pushButton_insert.setObjectName("pushButton_insert")
        self.horizontalLayout_4.addWidget(self.pushButton_insert)
        self.pushButton_delete = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton_delete.setMaximumSize(QtCore.QSize(60, 30))
        self.pushButton_delete.setObjectName("pushButton_delete")
        self.horizontalLayout_4.addWidget(self.pushButton_delete)
        self.pushButton_modify = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton_modify.setMaximumSize(QtCore.QSize(60, 30))
        self.pushButton_modify.setObjectName("pushButton_modify")
        self.horizontalLayout_4.addWidget(self.pushButton_modify)
        self.pushButton_query = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton_query.setMaximumSize(QtCore.QSize(60, 30))
        self.pushButton_query.setAutoDefault(False)
        self.pushButton_query.setDefault(False)
        self.pushButton_query.setObjectName("pushButton_query")
        self.horizontalLayout_4.addWidget(self.pushButton_query)
        self.verticalLayout.addLayout(self.horizontalLayout_4)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "访问数据库"))
        self.label_id.setText(_translate("Form", "商品号"))
        self.label_pname.setText(_translate("Form", "商品名"))
        self.label_brand.setText(_translate("Form", "品牌"))
        self.label_price.setText(_translate("Form", "价格"))
        self.label_stock.setText(_translate("Form", "库存量"))
        self.pushButton_first.setText(_translate("Form", "第一条"))
        self.pushButton_pre.setText(_translate("Form", "前一条"))
        self.pushButton_next.setText(_translate("Form", "后一条"))
        self.pushButton_last.setText(_translate("Form", "最后一条"))
        self.pushButton_insert.setText(_translate("Form", "插入"))
        self.pushButton_delete.setText(_translate("Form", "删除"))
        self.pushButton_modify.setText(_translate("Form", "修改"))
        self.pushButton_query.setText(_translate("Form", "查询"))